### ISSUE TITLE
Maybe some messages dropped in my code

### ISSUE THREAD

**Issue by NN-Binary** [RIAEvangelist/node-ipc#212] opened 2021-07-15 07:46 UTC
Hi,

I'm not sure the issue as I've tried on 3 different machines and the reliability of this module with IPC is very bad.
I've made a very basic test (2 files, client.js and server.js)

### CLIENT SIDE (client.js)
```js
import ipc from 'node-ipc';

var IPC_GLOBAL_CONFIG = {
    appspace: 'sup.',
    socketRoot: '/dev/shm/',
    id: 'hello',
    silent: true,
    logger: null,

    stopRetrying: false,
    retry: 5, // in ms, after how long it retries
    rawBuffer: true,
};

for (let IPCConfigKey in IPC_GLOBAL_CONFIG) {
    ipc.config[IPCConfigKey] = IPC_GLOBAL_CONFIG[IPCConfigKey]
}

let TargetID = 'Hello';

function SendMesssageViaIPC(TargetID, MessageBuffer) {

    try {
        ipc.of[TargetID].emit(MessageBuffer);
    }
    catch(e) {
        console.log(e)
    }
}


function ConnectToIPCServer(TargetID) {

    try {

        ipc.connectTo(TargetID, function() {

            ipc.of[TargetID].on('connect', function() {
                console.log('[IPC] [' + TargetID + '] Connected to server');
                for (let i=0; i < 100; i++) {
                    SendMesssageViaIPC(TargetID, Buffer.from('Hello!' + i))
                 }
            });
    
            ipc.of[TargetID].on('data', function(data) {
                console.log('Received message', data);
                
            });

            ipc.of[TargetID].on('error', function(err) {
                console.log('ERROR', err)
            });

        });

        ipc.on('error', function(err) {
            console.log(err)
        });

    }
    catch(e) {

    }

}

ConnectToIPCServer(TargetID);


setTimeout(function() {


    
}, 1000);

```

### SERVER SIDE (server.js)

```js
import ipc from 'node-ipc';

var IPC_GLOBAL_CONFIG = {
    appspace: 'sup.',
    socketRoot: '/dev/shm/',
    id: 'hello',
    silent: true,
    logger: null,
    stopRetrying: false,
    retry: 5, // in ms, after how long it retries
    rawBuffer: true,
};

for (let IPCConfigKey in IPC_GLOBAL_CONFIG) {
    ipc.config[IPCConfigKey] = IPC_GLOBAL_CONFIG[IPCConfigKey]
}


var MessageCount = 0;

let TargetID = 'yo';

var IPC_SERVERS = {};

function SendMesssageViaIPC(TargetID, MessageBuffer) {

    try {
        ipc.server.emit(IPC_SERVERS[TargetID], MessageBuffer);
    }
    catch(e) {
        console.log(e)
        // TODO => send back the msg on reconnect?
    }
    
}

function StartIPCServer(TargetID) {
    
    let IPCPath = ipc.config.socketRoot + ipc.config.appspace + TargetID;
    try {
        ipc.serve(IPCPath, function() {

            ipc.server.on('start', function(n){
                console.log('Server started');
            });

            ipc.server.on('connect', function(socket) {
  
                IPC_SERVERS[TargetID] = socket;
                console.log('[IPC] [' + TargetID + '] Client just connected');
            });
    
            ipc.server.on('data', function(data,socket) {
                MessageCount++;
            });

            ipc.server.on('error', function(err) {
                console.log('ERROR', err);
            });
        });

        ipc.server.start();
    }
    catch(e) {
        console.log(e);
    }


    
}



StartIPCServer("Hello");

setInterval(function() {
    console.log('IPC MEssage received:', MessageCount)
}, 1000);

```
If you run the test here, you'll see that you basically never receive 100 messages, probably 80, sometimes even 30/100 only.

Is there any way of making this library reliable? I'm choosing IPC for it's reliability actually but since switching from node process.send() to this library I'm missing about 30% of the messages.

**Comment by RuralDependencies** [comment] 2021-07-15 08:02
**It appears that this NPM does not offer any reliability with Buffers.**
After trying your code and setting rawBuffer to false, it works.

Indeed this is a serious issue.

**Comment by RIAEvangelist** [comment] 2021-07-15 17:38
I am not here to debug your code for you, I am sorry, you will need to make a simple example I can help you with. The simpler the code, the easier to find the issue in your code that is causing this. The cause could be in IPC or it could be in your code. We can not say until we identify the issue.

Please make a simple example and confirm that it is unreliable. Then make the example more complicated to tell where your code is allowing messages to be dropped. You may also want to set silent to false so you can better see what is happening.

**Comment by RIAEvangelist** [comment] 2021-07-15 22:49
Is it set to raw buffer by default?

**Comment by RIAEvangelist** [comment] 2021-07-15 22:49
If not, please help me figure out what note I need to make in the docs for
people

**Comment by NN-Binary** [comment] 2021-07-16 00:35
The problem is on node-ipc not supporting the computing of chunks when rawBuffer is true.
If you send 1,000 messages, they'll all arrive as 5 messages (all stacked together)

**Comment by RIAEvangelist** [comment] 2021-07-16 16:32
This is a duplicate of #197

Where it is made clear this is an issue in node. via [nodejs/help#521](https://github.com/nodejs/help/issues/521)

Your messages being certain it is the fault of my code without offering any help to fix the issue, is not in the opensource spirit. I hope that as time goes on and your skills improve, you will begin to write issues that contain help more than just pointing fingers in the ***free software*** you are using. 

Please contribute a fix or guidance on a fix if you can. Otherwise refer to [nodejs/help#521](https://github.com/nodejs/help/issues/521) as the previous users have to see this is an issue with node itself.

Thanks.

**Closed by RIAEvangelist** 2021-07-16 16:32 UTC
