### ISSUE TITLE
program not terminating correctly

### ISSUE THREAD

**Issue by philkunz** [RIAEvangelist/node-ipc#160] opened 2019-04-09 10:33 UTC
I wrote a little wrapper around node-ipc for easier client/server code reuse
For some reason stopping node-ipc won't work. In other words some server/client part is hindering nodejs from quitting.

Anything I need to add here -> https://gitlab.com/pushrocks/smartipc/blob/master/ts/index.ts#L65

**Comment by mifi** [comment] 2019-09-01 19:45
Same problem here. Something is not being closed correctly. When running `why-is-node-running` there is a open pipe, which i suspect to be the culprit:
```
# PIPEWRAP
(unknown stack trace)
```

**Comment by mifi** [comment] 2019-09-01 20:24
I think this is caused by the fact that net.Server.close does not close the connections, but it waits for all connections to close before terminating the server.
From https://nodejs.org/api/net.html#net_server_close_callback:
```
Stops the server from accepting new connections and keeps existing connections. This function is asynchronous, the server is finally closed when all connections are ended and the server emits a 'close' event. The optional callback will be called once the 'close' event occurs. Unlike that event, it will be called with an Error as its only argument if the server was not open when it was closed.
```


Could be solved by [unref](https://nodejs.org/api/net.html#net_server_unref), maybe with an option in node-ipc `unref: true/false`

**Comment by RIAEvangelist** [comment] 2019-12-02 09:05
Any more info on if this is needed or not? I am closing just because necrobump.

**Comment by mifi** [comment] 2019-12-02 11:09
Would be nice to have unref exposed thru the api

**Comment by RIAEvangelist** [comment] 2019-12-03 06:34
Ok

**Comment by RIAEvangelist** [comment] 2019-12-03 06:36
Should probably just default to that.

**Comment by RIAEvangelist** [comment] 2019-12-05 20:44
It looks like I do have an unlink value on the config object. Perhaps this can be used as well.

**Comment by mifi** [comment] 2019-12-06 02:26
I think defaulting is not so nice, because sometimes people want to wait for all the sockets to be closed properly (could take a few minutes). `unlink` config is for deleting the socket if it already exists, right? Imo should have a new config option `unref` that will call [unref](https://nodejs.org/api/net.html#net_server_unref) on shutdown

**Closed** 2020-11-12 18:28 UTC

**Comment by mifi** [comment] 2020-11-26 17:17
Is this implemented?

**Comment by RIAEvangelist** [comment] 2020-11-27 03:34
Can you not call unref on the socket for this?

**Comment by RIAEvangelist** [comment] 2020-11-27 03:34
If not it is something I would look into.

**Comment by mifi** [comment] 2020-11-27 22:01
If i remember correctly, we don't have access to the socket object

**Comment by joshuaalayon** [comment] 2022-03-17 21:06
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
