### ISSUE TITLE
Windows Sockets not sending EADDRINUSE in IPC error event

### ISSUE THREAD

**Issue by joncraig** [RIAEvangelist/node-ipc#112] opened 2017-03-17 16:45 UTC
I opened two ipc.serve Windows Sockets with the same path but it didn't raise EADDRINUSE in the IPC error event. Instead I saw this error from /dao/socketServer.js:
```
            this.log('server error',err);
                 ^
TypeError: this.log is not a function
```
Digging into /dao/socketServer.js function startServer() it looked like 'this' was going out of scope in the error handler?
```node
  this.server.on(
        'error',
        function(err){
            this.log('server error',err);

            this.publish(
                'error',
                err
            );
        }
    );
```
Changing socketServer.js with this worked for me:
```node
    var self=this;
    this.server.on(
        'error',
        function(err){
            self.log('server error',err);
            self.publish(
                'error',
                err
            );
        }
    );
```

**Comment by mvaldina** [comment] 2017-04-11 20:22
I'm facing a similar issue (two instances of node-ipc on the same TCP port).
I would like to know when this fix will be pushed on npm.

**Comment by cdl** [comment] 2017-04-12 23:07
👍 Running into this issue as well, and confirmed that the latest on `master` fixes it (with the changes in #113). Would love if we could get a small patch release with the fix in!

**Comment by RIAEvangelist** [comment] 2017-04-16 04:10
I'll finish up some of the modifications I am making for the ES6 version
and push tonight. When I do, if one of you guys could test to make sure
everything still works with your stuff that would be amazing. I'll only
push after the test suite passes, but want to have one of your input before
publishing.

**Comment by RIAEvangelist** [comment] 2017-04-16 06:05
tested and merged. thanks!

**Closed by RIAEvangelist** 2017-04-16 06:05 UTC

**Comment by ShubhenduVaid** [comment] 2022-02-09 11:19
Hi,
Looks like this issue has reappeared.
I am using the version 9.2.1 of node-ipc library.
While using Windows Sockets EADDRINUSE is not being sent to IPC error event.

I could see a log from SocketServer.js at
https://github.com/RIAEvangelist/node-ipc/blob/master/dao/socketServer.js#L289

but the error is not transmitted to error handler.

**Comment by joshuaalayon** [comment] 2022-03-17 21:09
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
